modLoader="javafml"
loaderVersion="[36,)"

license="MIT"

[[mods]]
modId="letmetest"
version="${file.jarVersion}"

displayName="letmetest"
logoFile="pack.png"

authors="Hellish Mods & Modern Modpacks"
credits="""
G_cat (Coding)
"""

description="Fixes the 1.16 forge bug that prevents multiplayer from working"

[[dependencies.letmetest]]
    modId="forge"
    mandatory=true

    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.letmetest]]
    modId="minecraft"
    mandatory=true

    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"